[workspace]
members = ["examples", "rqlite-rs", "rqlite-rs-macros", "rqlite-rs-core"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
thiserror = "1.0.58"
